### Obtener todos los empleados
GET http://localhost:8000/employee
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsInVzZXJuYW1lIjoid3R3aWxsIiwicGFzc3dvcmQiOiJhNzU0YTQ2NjI0ZWUxNWVjYzliMjBhNDVjZDI0ODc2ODI2MTdhYTZiNzQzNmFmYzk4ZDU4ZTkzMjEyZDdmYzQzOTc5NTU1ZTZkODQzYzdmZTg0MDhhZDZmZWNmYTYzMzZhYWEwY2I4N2IyMTQ4ODdjZmYwNjFhNGYwODU0OTM1YyIsImlhdCI6MTc0MDg4ODMwMSwiZXhwIjoxNzQwOTc0NzAxfQ.RuT3kif5R5cWTYHN-KZw2vWTw5xixuwdd69vv67Ho_I